import { isClient, isIOS } from '@vueuse/core';
type UtilValue = any;
type AnyFunction = (...args: UtilValue[]) => UtilValue;
export { isClient, isIOS };
export declare const isArray: (arg: any) => arg is any[];
export declare const toTypeString: (value: unknown) => string;
export declare const isObject: (val: unknown) => val is Record<UtilValue, UtilValue>;
export declare const isFunction: (val: unknown) => val is AnyFunction;
export declare const isUndefined: (val: UtilValue) => val is undefined;
export declare const isBoolean: (val: UtilValue) => val is boolean;
export declare const isNumber: (val: UtilValue) => val is number;
export declare const isString: (val: unknown) => val is string;
export declare const isEmpty: (val: unknown) => boolean;
export declare const isPlainObject: (val: any) => val is object;
export declare const hasOwn: (val: object, key: string | symbol) => key is keyof typeof val;
export declare const isKorean: (text: string) => boolean;
export declare const isElement: (e: unknown) => e is Element;
export declare const isPromise: <T = any>(a: unknown) => a is Promise<T>;
type Many<T> = T | ReadonlyArray<T>;
export declare const ensureArray: <T>(arr: Many<T>) => T[];
export declare const escapeStringRegexp: (string?: string) => string;
export declare function throwError(scope: string, m: string): never;
export declare function debugWarn(scope: string | Error, message?: string): void;
export declare function scrollIntoView(container: HTMLElement, selected: HTMLElement): void;
export declare const ValidateComponentsMap: {
    validating: import("vue").DefineComponent<{}, void, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
    success: import("vue").DefineComponent<{}, void, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
    error: import("vue").DefineComponent<{}, void, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
};
export declare const epPropKey = "__epPropKey";
export declare const buildProp: (prop: UtilValue, key?: string) => any;
export declare const buildProps: (props: UtilValue) => any;
export declare const findAllProTableParents: (targetElement: HTMLElement, matchStr: string) => HTMLElement | null | undefined;
