import { type Ref, type ComputedRef } from 'vue';
import type { ProComponentObject } from '../common.types';
import type { DeferredExcutorType } from '../utils/defer';
import type { KeyType, ProBaseTableProps, ProTablePageParams, ProTableGetRowKey } from './table.types';
import type { ProUnifyTableProviderProps } from './proTable.types';
type useRequestOptions<T extends ProComponentObject> = {
    deferReadyExecutor: DeferredExcutorType;
    showPage: boolean;
    waterfall: boolean;
    manualRequest?: boolean;
    pagination?: ProBaseTableProps['pagination'];
    internalIndex: ProUnifyTableProviderProps<T>['internalIndex'];
    rowKey: ProBaseTableProps['rowKey'];
    data: Ref<T[] | undefined>;
    params: Ref<ProComponentObject | undefined>;
    tableFirstRef: Ref<boolean>;
    onFirst: () => void;
    getEmptyColumnKeys: () => string[];
    getDefaultRow: () => boolean;
    getRowKey: ComputedRef<ProTableGetRowKey<T>>;
    isAutoPageSize: ComputedRef<boolean>;
} & Pick<ProBaseTableProps<T>, 'dataSource' | 'defaultData' | 'onLoad' | 'onRequestError' | 'postData' | 'defaultSearchForm' | 'onDataChange' | 'sliceRender'>;
declare const useRequest: <T extends ProComponentObject>(request: ProBaseTableProps<T>["request"], options: useRequestOptions<T>) => {
    fetchMethod: (isData?: boolean) => Promise<void>;
    selectFetch: (cb: () => void) => Promise<void> | undefined;
    pureFetch: (pageInfo: ProTablePageParams) => Promise<{
        data: T[];
        scrollId: any;
        hasMore: any;
    }> | Promise<{
        data: T[];
        hasMore: boolean;
    }>;
    setPage: (changedPage: ProTablePageParams) => void;
    setSearchForm: (formValues: ProComponentObject) => void;
    clearSearchForm: () => void;
    setLoading: (v: boolean) => void;
    setTableData: (data: T[], isCover?: boolean) => void;
    getTableData: () => T[];
    getRealTableData: () => T[];
    getTableDataHasKey: () => T[];
    getRealTableDataHasKey: () => T[];
    getTableDataAndChildren: () => T[];
    getTableDataAllChildren: (list?: T[]) => T[];
    getTableChildrenByRowValue: (keyValue: KeyType) => T[];
    getParentByRowValue: (keyValue: KeyType) => T | undefined;
    resetRequest: () => void;
    setFirst: (v: boolean) => void;
    getTableDataSize: () => number;
    getRowDataByIndex: (index: number) => T;
    loading: Ref<boolean, boolean>;
    error: Ref<string, string>;
    tableData: import("vue").ShallowRef<T[], T[]>;
    pageInfo: {
        currentPage?: number | undefined;
        pageSize?: number | undefined;
        total?: number | undefined;
        scrollId?: string | undefined;
        hasMore?: boolean | undefined;
    };
    searchForm: ProComponentObject;
    first: Ref<boolean, boolean>;
};
export default useRequest;
