import type { FormRules, FormItemProps } from 'element-plus';
import type { Ref, Reactive } from 'vue';
import type { DisplayEnum, EffectType, EffectContextType, ProFormProps, EffectCallbackType, ProFormValueType } from './form.types';
import type { ProComponentObject } from '../common.types';
type StateType = {
    display?: DisplayEnum;
    label?: string;
    required?: boolean;
    rules?: FormItemProps['rules'];
    valueType?: string;
} & Record<string, any>;
declare class FormModel {
    private key;
    private state;
    constructor(key: string, state: StateType);
    setStates(state: StateType): void;
    getState(stateKey: string): any;
    setState(stateKey: string | string[], value: any): StateType;
}
declare class FormStore<T extends ProComponentObject = ProComponentObject> {
    private values;
    private rules;
    private models;
    private instances;
    private effects;
    private effectCbs;
    private mode;
    private removeValues;
    private keyboard;
    constructor(values?: T, rules?: FormRules, mode?: ProFormProps<T>['mode'], keyboard?: boolean);
    addModel(key: string, state: StateType): void;
    getModel(key: string): FormModel;
    removeModel(key: string): void;
    addEffectCb(sourceKey: string, cb: EffectCallbackType): void;
    getEffectCb(sourceKey: string): EffectCallbackType;
    removeEffectCb(sourceKey: string): void;
    addEffect(sourceKey: string, effects?: EffectType[]): void;
    removeEffect(sourceKey: string): void;
    getEffectContext(sourceKey: string, targetKeys: string[], isArr: boolean): EffectContextType;
    executeEffect(obj: EffectType['decorator'] | EffectType['component'], context: EffectContextType, tar: string, isComponent?: boolean): void;
    runEffects(sourceKey: string, trigger: EffectType['trigger']): void;
    setEffect(key: string, stateKey: string, value: any, isComponent?: boolean): void;
    addInstance(key: string, instance: any, getInstance: () => any): void;
    removeInstance(key: string): void;
    getInstances(): Record<string, any>[];
    getInstancesRef(): Ref<Record<string, any>[], Record<string, any>[]>;
    getValues(): Reactive<T>;
    getNormalValues(): any;
    getLogicValues(): any;
    setValues(values: Partial<T>, isCover?: boolean): void;
    setSyncValues(values: Partial<ProFormValueType>): void;
    deleteValues(values: ProFormValueType): void;
    getValue(key: string): any;
    setValue(key: keyof T, value: any): void;
    removeValue(key: string, obj?: ProFormValueType): void;
    removeSnapshot(key: string): void;
    removeSnapshotValue(key: string): void;
    setRules(rules: FormRules): void;
    getRule(key: string): any;
    setRule(key: string, rule: FormItemProps['rules']): void;
    getMode(): import("..").ProFieldFCMode | undefined;
    setMode(mode: ProFormProps<T>['mode']): void;
    getKeyboard(): boolean;
    setKeyboard(keyboard: boolean): void;
}
export default FormStore;
