import type { StoryObj } from '@storybook/vue3';
import { ProSelect } from '../index';
declare const meta: {
    title: string;
    component: {
        new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<{
            modelValue?: any;
            keyword?: string;
            defaultLabel?: string | string[];
            contentWidth?: number;
            contentHeight?: number;
            defaultValueEnum?: import("../proField").ProSchemaValueEnumType[];
            valueEnum?: import("../proField").ProSchemaValueEnumType[];
            handleValueEnumChange?: (valueEnum: import("../proField").ProSchemaValueEnumType[]) => void;
            manualRequest?: boolean;
            waterfall?: boolean;
            tableProps?: Partial<import("../proTable").ProTableProps<import("../common.types").ProComponentObject>> | undefined;
            labelKey?: string | ((v: import("../common.types").ProComponentObject) => string) | undefined;
            name?: string;
            id?: string;
            autocomplete?: string;
            automaticDropdown?: boolean;
            size?: import("element-plus").SelectProps["size"];
            effect?: import("element-plus").SelectProps["effect"];
            disabled?: boolean;
            clearable?: boolean;
            filterable?: boolean;
            allowCreate?: boolean;
            loadingText?: string;
            popperClass?: string;
            popperOptions?: Partial<import("element-plus").Options>;
            noMatchText?: string;
            noDataText?: string;
            remoteMethod?: (v?: any) => Promise<any>;
            params?: Record<string, any>;
            filterMethod?: (v?: any) => void;
            multiple?: boolean;
            multipleLimit?: number;
            placeholder?: string;
            defaultFirstOption?: boolean;
            reserveKeyword?: boolean;
            valueKey?: string;
            collapseTags?: boolean;
            collapseTagsTooltip?: boolean;
            maxCollapseTags?: number;
            teleported?: boolean;
            appendTo?: import("element-plus").SelectProps["appendTo"];
            persistent?: boolean;
            clearIcon?: import("element-plus").SelectProps["clearIcon"];
            fitInputWidth?: boolean;
            suffixIcon?: import("element-plus").SelectProps["suffixIcon"];
            tagType?: import("element-plus").SelectProps["tagType"];
            tagEffect?: import("element-plus").SelectProps["tagEffect"];
            validateEvent?: boolean;
            remoteShowSuffix?: boolean;
            offset?: number;
            placement?: import("element-plus").SelectProps["placement"];
            fallbackPlacements?: import("element-plus").SelectProps["fallbackPlacements"];
            tabindex?: string | number;
            showArrow?: boolean;
            keywordRequest?: boolean;
            handleKeyDown?: (e: KeyboardEvent) => boolean;
            checkAll?: boolean;
            checkAllText?: string;
        }> & Readonly<{
            [x: `on${Capitalize<any>}`]: ((...args: any) => any) | undefined;
        }>, {
            selectedLabel: import("vue").ComputedRef<string | string[]>;
            getText: (v: any) => any;
            focus: () => void;
            blur: () => void;
        }, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
            [x: string]: any;
        } & {
            [x: string]: any;
        }, import("vue").PublicProps, {
            disabled: boolean;
            tabindex: string | number;
            autocomplete: string;
            effect: import("element-plus").SelectProps["effect"];
            offset: number;
            placement: import("element-plus").SelectProps["placement"];
            popperClass: string;
            popperOptions: Partial<import("element-plus").Options>;
            showArrow: boolean;
            fallbackPlacements: import("element-plus").SelectProps["fallbackPlacements"];
            teleported: boolean;
            multiple: boolean;
            waterfall: boolean;
            validateEvent: boolean;
            persistent: boolean;
            manualRequest: boolean;
            valueKey: string;
            automaticDropdown: boolean;
            clearable: boolean;
            filterable: boolean;
            allowCreate: boolean;
            multipleLimit: number;
            defaultFirstOption: boolean;
            reserveKeyword: boolean;
            collapseTagsTooltip: boolean;
            maxCollapseTags: number;
            clearIcon: import("element-plus").SelectProps["clearIcon"];
            fitInputWidth: boolean;
            suffixIcon: import("element-plus").SelectProps["suffixIcon"];
            tagType: import("element-plus").SelectProps["tagType"];
            tagEffect: import("element-plus").SelectProps["tagEffect"];
            remoteShowSuffix: boolean;
            checkAll: boolean;
            checkAllText: string;
            contentHeight: number;
            keywordRequest: boolean;
        }, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
            P: {};
            B: {};
            D: {};
            C: {};
            M: {};
            Defaults: {};
        }, Readonly<{
            modelValue?: any;
            keyword?: string;
            defaultLabel?: string | string[];
            contentWidth?: number;
            contentHeight?: number;
            defaultValueEnum?: import("../proField").ProSchemaValueEnumType[];
            valueEnum?: import("../proField").ProSchemaValueEnumType[];
            handleValueEnumChange?: (valueEnum: import("../proField").ProSchemaValueEnumType[]) => void;
            manualRequest?: boolean;
            waterfall?: boolean;
            tableProps?: Partial<import("../proTable").ProTableProps<import("../common.types").ProComponentObject>> | undefined;
            labelKey?: string | ((v: import("../common.types").ProComponentObject) => string) | undefined;
            name?: string;
            id?: string;
            autocomplete?: string;
            automaticDropdown?: boolean;
            size?: import("element-plus").SelectProps["size"];
            effect?: import("element-plus").SelectProps["effect"];
            disabled?: boolean;
            clearable?: boolean;
            filterable?: boolean;
            allowCreate?: boolean;
            loadingText?: string;
            popperClass?: string;
            popperOptions?: Partial<import("element-plus").Options>;
            noMatchText?: string;
            noDataText?: string;
            remoteMethod?: (v?: any) => Promise<any>;
            params?: Record<string, any>;
            filterMethod?: (v?: any) => void;
            multiple?: boolean;
            multipleLimit?: number;
            placeholder?: string;
            defaultFirstOption?: boolean;
            reserveKeyword?: boolean;
            valueKey?: string;
            collapseTags?: boolean;
            collapseTagsTooltip?: boolean;
            maxCollapseTags?: number;
            teleported?: boolean;
            appendTo?: import("element-plus").SelectProps["appendTo"];
            persistent?: boolean;
            clearIcon?: import("element-plus").SelectProps["clearIcon"];
            fitInputWidth?: boolean;
            suffixIcon?: import("element-plus").SelectProps["suffixIcon"];
            tagType?: import("element-plus").SelectProps["tagType"];
            tagEffect?: import("element-plus").SelectProps["tagEffect"];
            validateEvent?: boolean;
            remoteShowSuffix?: boolean;
            offset?: number;
            placement?: import("element-plus").SelectProps["placement"];
            fallbackPlacements?: import("element-plus").SelectProps["fallbackPlacements"];
            tabindex?: string | number;
            showArrow?: boolean;
            keywordRequest?: boolean;
            handleKeyDown?: (e: KeyboardEvent) => boolean;
            checkAll?: boolean;
            checkAllText?: string;
        }> & Readonly<{
            [x: `on${Capitalize<any>}`]: ((...args: any) => any) | undefined;
        }>, {
            selectedLabel: import("vue").ComputedRef<string | string[]>;
            getText: (v: any) => any;
            focus: () => void;
            blur: () => void;
        }, {}, {}, {}, {
            disabled: boolean;
            tabindex: string | number;
            autocomplete: string;
            effect: import("element-plus").SelectProps["effect"];
            offset: number;
            placement: import("element-plus").SelectProps["placement"];
            popperClass: string;
            popperOptions: Partial<import("element-plus").Options>;
            showArrow: boolean;
            fallbackPlacements: import("element-plus").SelectProps["fallbackPlacements"];
            teleported: boolean;
            multiple: boolean;
            waterfall: boolean;
            validateEvent: boolean;
            persistent: boolean;
            manualRequest: boolean;
            valueKey: string;
            automaticDropdown: boolean;
            clearable: boolean;
            filterable: boolean;
            allowCreate: boolean;
            multipleLimit: number;
            defaultFirstOption: boolean;
            reserveKeyword: boolean;
            collapseTagsTooltip: boolean;
            maxCollapseTags: number;
            clearIcon: import("element-plus").SelectProps["clearIcon"];
            fitInputWidth: boolean;
            suffixIcon: import("element-plus").SelectProps["suffixIcon"];
            tagType: import("element-plus").SelectProps["tagType"];
            tagEffect: import("element-plus").SelectProps["tagEffect"];
            remoteShowSuffix: boolean;
            checkAll: boolean;
            checkAllText: string;
            contentHeight: number;
            keywordRequest: boolean;
        }>;
        __isFragment?: never;
        __isTeleport?: never;
        __isSuspense?: never;
    } & import("vue").ComponentOptionsBase<Readonly<{
        modelValue?: any;
        keyword?: string;
        defaultLabel?: string | string[];
        contentWidth?: number;
        contentHeight?: number;
        defaultValueEnum?: import("../proField").ProSchemaValueEnumType[];
        valueEnum?: import("../proField").ProSchemaValueEnumType[];
        handleValueEnumChange?: (valueEnum: import("../proField").ProSchemaValueEnumType[]) => void;
        manualRequest?: boolean;
        waterfall?: boolean;
        tableProps?: Partial<import("../proTable").ProTableProps<import("../common.types").ProComponentObject>> | undefined;
        labelKey?: string | ((v: import("../common.types").ProComponentObject) => string) | undefined;
        name?: string;
        id?: string;
        autocomplete?: string;
        automaticDropdown?: boolean;
        size?: import("element-plus").SelectProps["size"];
        effect?: import("element-plus").SelectProps["effect"];
        disabled?: boolean;
        clearable?: boolean;
        filterable?: boolean;
        allowCreate?: boolean;
        loadingText?: string;
        popperClass?: string;
        popperOptions?: Partial<import("element-plus").Options>;
        noMatchText?: string;
        noDataText?: string;
        remoteMethod?: (v?: any) => Promise<any>;
        params?: Record<string, any>;
        filterMethod?: (v?: any) => void;
        multiple?: boolean;
        multipleLimit?: number;
        placeholder?: string;
        defaultFirstOption?: boolean;
        reserveKeyword?: boolean;
        valueKey?: string;
        collapseTags?: boolean;
        collapseTagsTooltip?: boolean;
        maxCollapseTags?: number;
        teleported?: boolean;
        appendTo?: import("element-plus").SelectProps["appendTo"];
        persistent?: boolean;
        clearIcon?: import("element-plus").SelectProps["clearIcon"];
        fitInputWidth?: boolean;
        suffixIcon?: import("element-plus").SelectProps["suffixIcon"];
        tagType?: import("element-plus").SelectProps["tagType"];
        tagEffect?: import("element-plus").SelectProps["tagEffect"];
        validateEvent?: boolean;
        remoteShowSuffix?: boolean;
        offset?: number;
        placement?: import("element-plus").SelectProps["placement"];
        fallbackPlacements?: import("element-plus").SelectProps["fallbackPlacements"];
        tabindex?: string | number;
        showArrow?: boolean;
        keywordRequest?: boolean;
        handleKeyDown?: (e: KeyboardEvent) => boolean;
        checkAll?: boolean;
        checkAllText?: string;
    }> & Readonly<{
        [x: `on${Capitalize<any>}`]: ((...args: any) => any) | undefined;
    }>, {
        selectedLabel: import("vue").ComputedRef<string | string[]>;
        getText: (v: any) => any;
        focus: () => void;
        blur: () => void;
    }, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
        [x: string]: any;
    } & {
        [x: string]: any;
    }, string, {
        disabled: boolean;
        tabindex: string | number;
        autocomplete: string;
        effect: import("element-plus").SelectProps["effect"];
        offset: number;
        placement: import("element-plus").SelectProps["placement"];
        popperClass: string;
        popperOptions: Partial<import("element-plus").Options>;
        showArrow: boolean;
        fallbackPlacements: import("element-plus").SelectProps["fallbackPlacements"];
        teleported: boolean;
        multiple: boolean;
        waterfall: boolean;
        validateEvent: boolean;
        persistent: boolean;
        manualRequest: boolean;
        valueKey: string;
        automaticDropdown: boolean;
        clearable: boolean;
        filterable: boolean;
        allowCreate: boolean;
        multipleLimit: number;
        defaultFirstOption: boolean;
        reserveKeyword: boolean;
        collapseTagsTooltip: boolean;
        maxCollapseTags: number;
        clearIcon: import("element-plus").SelectProps["clearIcon"];
        fitInputWidth: boolean;
        suffixIcon: import("element-plus").SelectProps["suffixIcon"];
        tagType: import("element-plus").SelectProps["tagType"];
        tagEffect: import("element-plus").SelectProps["tagEffect"];
        remoteShowSuffix: boolean;
        checkAll: boolean;
        checkAllText: string;
        contentHeight: number;
        keywordRequest: boolean;
    }, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
        $slots: {
            prefix?: (props: {}) => any;
        } & {
            tag?: (props: {}) => any;
        } & {
            label?: (props: {
                label: string | number | boolean;
                value: any;
            }) => any;
        } & {
            label?: (props: {
                label: string | number | boolean;
                value: any;
            }) => any;
        } & {
            label?: (props: {
                label: string;
                value: any;
            }) => any;
        } & {
            header?: (props: {}) => any;
        } & {
            loading?: (props: {}) => any;
        } & {
            empty?: (props: {}) => any;
        } & {
            footer?: (props: {}) => any;
        };
    });
    tags: string[];
    parameters: {
        docs: {
            description: {
                component: string;
            };
        };
    };
};
export default meta;
type Story = StoryObj<typeof ProSelect>;
export declare const Basic: Story;
export declare const ValueObject: Story;
export declare const Control: Story;
export declare const Waterfall: Story;
export declare const Table: Story;
