import type { Meta } from '@storybook/vue3';
import { ProForm } from '../../index';
import { Basic } from './base';
import { Layout } from './layout';
import { Effect } from './effect';
import { Value } from './value';
import { Table } from './table';
import { Tag } from './jsx';
declare const meta: Meta<typeof ProForm>;
export default meta;
export { Basic };
export { Layout };
export { Effect };
export { Value };
export { Table };
export { Tag };
